name: NoExperienceMod
version: 1.0.0
description: This plugin allows ExperienceMod 2.3.0 to modify the new Minecraft 1.3.1 experience system.
author: Comphenix
website: http://www.comphenix.net/NoExperienceMod

main: com.comphenix.noxp.NoExpMod
database: false

commands:

permissions: